default environment: test

basic configuration:
  browser name: CHROME
  headless: false
  implicit wait: 3
  explicit wait: 30
  faker language: pl-PL
  browser option maximized: start-maximized
  browser option remote allow: --remote-allow-origins=*

environments:
  - env name: test
    web url: http://146.59.32.4/index.php
    cart url part: ?controller=cart&action=show
    user social title: MR
    user first name: Słoń
    user last name: Trąbalski
    user email: strabalski@test.pl
    user password: 12345678
    home address: Sheraton Ave
    home city: Austin
    home zipcode: 73301
    home state: Texas
    invoice address: Courthouse Square
    invoice city: Oxford
    invoice zipcode: 38655
    invoice state: Mississippi
